CREATE TABLE [dbo].[School] (
	SchoolID INT PRIMARY KEY,
	Name NVARCHAR (75) NOT NULL,
	Street1 NVARCHAR (200) NOT NULL,
	Street2 NVARCHAR (200) NOT NULL,
	City NVARCHAR (50) NOT NULL,
	State VARCHAR (50) NOT NULL
	);